### ISSUE TITLE
Instrument data encryption

### ISSUE THREAD

**Issue by peteknowsai** [API-market/ore-protocol#14]
@surabhil commented on [Wed Nov 14 2018](https://github.com/API-market/archive-ore-protocol/issues/99)

- Add "encrypedWith" field to instrument_data
- Update licenseapi to take in following inputs in adddition to existing inputs:
   - additionalUrlParams to add to voucher's additionalUrlParams
   - encrypt to specify whether to encrypt the additionalUrlParams

More details in the following doc:
https://www.notion.so/aikon/Instrument-encryption-discussion-7d437e39c70942eca797e573f0f766ae

**Comment by surabhil** [comment]
Done and deployed in production.
