### ISSUE TITLE
Rights registry should have a remove right action (for unused rights)

### ISSUE THREAD

**Issue by peteknowsai** [API-market/ore-protocol#15]
@traylewin commented on [Wed Oct 24 2018](https://github.com/API-market/archive-ore-protocol/issues/87)

The rights registry should be able to remove a right if it is not referenced by any instrument. 

We should only do this if it's relatively easy to do. 

We might also consider adding a 'retired' flag to designate that a right is no longer usable.

**Comment by surabhil** [comment]
Done in previous release.
