### ISSUE TITLE
Update licensapi function to allow user to specify additionalUrlParams that can be added to the voucher

### ISSUE THREAD

**Issue by peteknowsai** [API-market/ore-protocol#17]
@surabhil commented on [Fri Nov 16 2018](https://github.com/API-market/archive-ore-protocol/issues/100)

- Add additionalUrlParams parameters to the LicenseApi action:
- Push back the additionalUrlParams parameters block to the additionalUrlParams coming from the offer if any.

additionalUrlParams are the optional values that are combined with any additionalUrlParams that are already defined in the offer and the combined result appears in the output voucher’s additional_url_params

These could optionally have the following structure:
"additional_url_params": [
{ "params": [{"name":"encryptedWith","value":"user1@authVerifier", {"name": "param1", "value": "v1" },{ "name": "param2", "value": "v2" }]

**Comment by surabhil** [comment]
Done and deployed in production. Code present in the apimarket repo
